env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/function-component-definition: "off",
  arrow-body-style: "off",
  comma-dangle: "warn",
  no-param-reassign: "off",
  react/prop-types: "off"
}
